// Generated by the Cloudflare adapter, outside the asset directory.
// @ts-ignore generated during build
import app from '../.svelte-kit/svelte-worker.js';
import type { ExecutionContext } from '@cloudflare/workers-types';
import { authenticateRequest } from './gate';
import type { AuthEnv } from './auth';

export default {
	fetch(request: Request, env: AuthEnv, ctx: ExecutionContext) {
		return authenticateRequest(request, env, () => app.fetch(request, env, ctx));
	}
};
