import { expect, test } from '@playwright/test';
import { readdirSync } from 'node:fs';

test('Pagefind exposes real course and tag filters, including #tag search', async ({ page }) => {
	await page.goto('/sp26-cs544/README');
	const filters = await page.evaluate(async () => {
		// @ts-expect-error generated by Pagefind after the SvelteKit build
		const pagefind = await import('/pagefind/pagefind.js');
		await pagefind.init();
		return pagefind.filters();
	});

	expect(Object.keys(filters.course ?? {})).toContain('sp26-cs544');
	expect(Object.keys(filters.course ?? {})).not.toContainEqual(expect.stringContaining(', tag:'));
	expect(Object.keys(filters.tag ?? {})).toContain('cs544');
	expect(Object.keys(filters.tag ?? {}).length).toBeGreaterThan(150);

	await page.keyboard.press('Control+k');
	await page.getByPlaceholder('Search… or #tag').fill('#cs544');
	await expect(page.getByLabel('Filter by tag')).toContainText('cs544');
	await expect(page.locator('[data-command-group-items]').first()).toBeVisible();
});

test('graph survives navigation, fullscreen, and theme changes without browser errors', async ({
	page
}) => {
	await page.setViewportSize({ width: 1440, height: 900 });
	const errors: string[] = [];
	page.on('pageerror', (error) => errors.push(error.stack ?? error.message));

	const prerendered = await page.request.get('/sp26-cs544/README');
	expect(await prerendered.text()).toContain('data-graph-outer');

	await page.goto('/sp26-cs544/README');
	const graph = page.getByRole('region', { name: 'Graph view' });
	const graphOuter = graph.locator('[data-graph-outer]');
	await expect(graphOuter).toBeVisible();
	await expect(graph.getByRole('heading', { name: 'Graph View' })).toBeVisible();
	const graphBox = await graphOuter.boundingBox();
	expect(graphBox?.width ?? 0).toBeGreaterThanOrEqual(315);
	expect(graphBox?.height).toBe(250);

	const toc = page.getByRole('navigation', { name: 'On this page' });
	await expect(toc).toBeVisible();
	const graphPrecedesToc = await graph.evaluate((element) => {
		const tocElement = document.querySelector('nav[aria-label="On this page"]');
		return Boolean(
			tocElement && element.compareDocumentPosition(tocElement) & Node.DOCUMENT_POSITION_FOLLOWING
		);
	});
	expect(graphPrecedesToc).toBe(true);
	const backlinks = page.locator('main [data-island="backlinks"]');
	await expect(backlinks.getByRole('heading', { name: 'Linked to this page' })).toBeVisible();
	await expect(page.locator('.doc-sidebar-right [data-island="backlinks"]')).toHaveCount(0);

	const localCanvas = page.locator('[aria-label="Graph view"] canvas');
	await expect(localCanvas).toBeVisible();
	const graphView = graph.getByRole('img', { name: 'Knowledge graph' });
	await expect(graphView).toHaveAttribute('data-graph-ready', 'true');
	expect(Number(await graphView.getAttribute('data-graph-nodes'))).toBeGreaterThan(1);
	expect(Number(await graphView.getAttribute('data-graph-links'))).toBeGreaterThan(0);
	const currentNodePosition = await graphView.evaluate((element) => ({
		x: Number(element.getAttribute('data-graph-current-x')),
		y: Number(element.getAttribute('data-graph-current-y')),
		centerX: (element.querySelector('canvas')?.clientWidth ?? 0) / 2,
		centerY: (element.querySelector('canvas')?.clientHeight ?? 0) / 2
	}));
	expect(currentNodePosition.x).toBeCloseTo(currentNodePosition.centerX, 5);
	expect(currentNodePosition.y).toBeCloseTo(currentNodePosition.centerY, 5);
	const box = await localCanvas.boundingBox();
	expect(box?.width ?? 0).toBeGreaterThanOrEqual(313);

	await page.getByRole('button', { name: 'Expand graph' }).click();
	await expect(page.locator('[role="dialog"] canvas')).toBeVisible();
	await page.getByRole('button', { name: 'Close' }).click();

	const link = page.locator('article a.internal[href="/sp26-cs544/lectures/lecture-01"]').first();
	await link.hover();
	await expect(page.locator('.popover.active-popover')).toBeVisible();
	await page
		.getByRole('button', { name: 'Toggle dark mode' })
		.filter({ visible: true })
		.first()
		.click();
	await link.click();
	await page.waitForURL('**/sp26-cs544/lectures/lecture-01');
	await page.waitForTimeout(500);
	expect(errors).toEqual([]);
});

test('compact page tools stay above the article and open the graph', async ({ page }) => {
	await page.setViewportSize({ width: 1000, height: 800 });
	await page.goto('/sp26-cs544/README');

	const main = page.locator('main.doc-main');
	const graph = page.getByRole('region', { name: 'Graph view' });
	await expect(graph).toBeHidden();
	await expect(page.getByRole('navigation', { name: 'On this page' })).toBeHidden();

	const mainBox = await main.boundingBox();
	const toolsBox = await page.locator('.doc-sidebar-right').boundingBox();
	expect(toolsBox!.y + toolsBox!.height).toBeLessThanOrEqual(mainBox!.y);
	await page.getByRole('button', { name: 'Open global graph' }).click();
	await expect(page.locator('[role="dialog"] canvas')).toBeVisible();
	await page.getByRole('button', { name: 'Close', exact: true }).click();
	await page.locator('.doc-compact-outline summary').click();
	await expect(page.getByRole('navigation', { name: 'On this page' })).toBeVisible();
});

test('breakpoint boundaries preserve reading width and usable navigation', async ({ page }) => {
	for (const width of [799, 800, 801, 1023, 1024, 1199, 1200, 1439, 1440]) {
		await page.setViewportSize({ width, height: 900 });
		await page.goto('/sp26-cs544/README');
		const article = await page.locator('article').boundingBox();
		expect(article!.width).toBeGreaterThanOrEqual(650);
		if (width < 1024) {
			const toggle = page.getByRole('button', { name: 'Toggle navigation' });
			await toggle.click();
			await expect(toggle).toHaveAttribute('aria-expanded', 'true');
			await expect(page.getByRole('navigation', { name: 'Documentation' })).toBeInViewport();
			await page.getByRole('button', { name: 'Close navigation', exact: true }).click();
		}
	}
	await page.goto('/tags');
	await expect(page.locator('.doc-sidebar-right')).toHaveCount(0);
	await page.goto('/sp26-cs544');
	await expect(page.locator('.doc-sidebar-right')).toHaveCount(0);
});

test('desktop rails stay pinned to both viewport edges on wide screens', async ({ page }) => {
	await page.setViewportSize({ width: 1920, height: 900 });
	await page.goto('/sp26-cs544/README');

	const sidebarBox = await page.locator('.doc-sidebar-left').boundingBox();
	const mainContentBox = await page.locator('.doc-main > div').boundingBox();
	const rightRail = page.locator('.doc-sidebar-right');
	const rightRailBox = await rightRail.boundingBox();
	const shellBox = await page.locator('.doc-shell').boundingBox();
	expect(sidebarBox?.x).toBe(0);
	expect(shellBox?.x).toBe(0);
	expect(shellBox?.width).toBe(1920);
	expect((rightRailBox?.x ?? 0) + (rightRailBox?.width ?? 0)).toBe(1920);
	expect((mainContentBox?.x ?? 0) + (mainContentBox?.width ?? 0) / 2).toBe(960);

	const panelStyle = await rightRail.evaluate((element) => {
		const style = getComputedStyle(element);
		const leftRail = document.querySelector<HTMLElement>('.doc-sidebar-left');
		return {
			background: style.backgroundColor,
			leftBackground: leftRail ? getComputedStyle(leftRail).backgroundColor : null,
			border: style.borderLeftWidth,
			borderStyle: style.borderLeftStyle,
			height: style.height,
			position: style.position
		};
	});
	expect(panelStyle).toEqual({
		background: panelStyle.leftBackground,
		leftBackground: panelStyle.leftBackground,
		border: '1px',
		borderStyle: 'solid',
		height: '900px',
		position: 'sticky'
	});
	expect(
		await page.locator('.doc-toc').evaluate((element) => getComputedStyle(element).borderTopWidth)
	).toBe('1px');
});

test('Mermaid diagrams retain copy and fullscreen pan/zoom controls', async ({ page }) => {
	await page.goto('/sp26-cs544/lectures/lecture-25');
	const sourceBlocks = page.locator('pre:has(> code.mermaid)');
	const count = await sourceBlocks.count();
	expect(count).toBeGreaterThan(0);

	for (let index = 0; index < count; index++) {
		await sourceBlocks.nth(index).scrollIntoViewIfNeeded();
	}
	// The 200px observer margin can render several adjacent diagrams together.
	await expect(page.locator('.mermaid-inline-content > svg')).toHaveCount(count, {
		timeout: 15_000
	});
	await expect(page.getByRole('button', { name: 'Expand diagram' })).toHaveCount(count);
	await expect(page.getByRole('button', { name: 'Copy diagram source' })).toHaveCount(count);

	await page.getByRole('button', { name: 'Expand diagram' }).first().click();
	const dialog = page.getByRole('dialog', { name: 'Expanded diagram' });
	await expect(dialog).toBeVisible();
	await dialog.getByRole('button', { name: 'Zoom in' }).click();
	await expect(dialog.locator('.mermaid-modal-content')).toHaveAttribute('style', /scale\(1\.1\)/);
	await dialog.getByRole('button', { name: 'Reset zoom' }).click();
	await expect(dialog.locator('.mermaid-modal-content')).toHaveAttribute('style', /scale\(1\)/);
	await page.keyboard.press('Escape');
	await expect(dialog).toBeHidden();
});

test('system theme and heading deep links work', async ({ page }) => {
	await page.goto('/sp26-cs544/lectures/lecture-25');
	await expect(page.locator('html')).not.toHaveClass(/dark/);
	const heading = page.locator('article h2[id]').first();
	const anchor = heading.locator('a.heading-anchor');
	await expect(anchor).toHaveAttribute('href', /^#/);
	await anchor.click();
	await expect(page).toHaveURL(/#.+/);
});

test('Cloudflare asset headers and canonical URLs are configured', async ({ request }) => {
	const pageResponse = await request.get('/sp26-cs544/README');
	expect(pageResponse.headers()['x-content-type-options']).toBe('nosniff');
	expect(pageResponse.headers()['x-frame-options']).toBe('DENY');
	expect(pageResponse.headers()['x-robots-tag']).toContain('noindex');

	const graphResponse = await request.get('/graph.json');
	expect(graphResponse.headers()['cache-control']).toContain('max-age=300');

	const pagefindFilter = readdirSync('.svelte-kit/cloudflare/pagefind/filter')[0];
	const filterResponse = await request.get(`/pagefind/filter/${pagefindFilter}`);
	expect(filterResponse.headers()['cache-control']).toContain('immutable');

	const trailing = await request.get('/sp26-cs544/README/', { maxRedirects: 0 });
	expect(trailing.status()).toBe(307);
	expect(trailing.headers().location).toBe('/sp26-cs544/README');
});
