import { expect, test } from '@playwright/test';
import { readdirSync } from 'node:fs';

test('Pagefind exposes real course and tag filters, including #tag search', async ({ page }) => {
	await page.goto('/sp26-cs544/README');
	const filters = await page.evaluate(async () => {
		// @ts-expect-error generated by Pagefind after the SvelteKit build
		const pagefind = await import('/pagefind/pagefind.js');
		await pagefind.init();
		return pagefind.filters();
	});

	expect(Object.keys(filters.course ?? {})).toContain('sp26-cs544');
	expect(Object.keys(filters.course ?? {})).not.toContainEqual(expect.stringContaining(', tag:'));
	expect(Object.keys(filters.tag ?? {})).toContain('cs544');
	expect(Object.keys(filters.tag ?? {}).length).toBeGreaterThan(150);

	await page.keyboard.press('Control+k');
	await page.getByPlaceholder('Search… or #tag').fill('#cs544');
	await expect(page.getByLabel('Filter by tag')).toContainText('cs544');
	await expect(page.locator('[data-command-group-items]').first()).toBeVisible();
});

test('graph survives the Quartz interaction sequence without browser errors', async ({ page }) => {
	const errors: string[] = [];
	page.on('pageerror', (error) => errors.push(error.stack ?? error.message));

	await page.goto('/sp26-cs544/README');
	const localCanvas = page.locator('[aria-label="Graph view"] canvas');
	await expect(localCanvas).toBeVisible();
	const box = await localCanvas.boundingBox();
	expect(box?.width ?? 0).toBeGreaterThanOrEqual(270);

	await page.getByRole('button', { name: 'Open global graph' }).click();
	await expect(page.locator('[role="dialog"] canvas')).toBeVisible();
	await page.getByRole('button', { name: 'Close' }).click();

	const link = page.locator('article a.internal[href="/sp26-cs544/lectures/lecture-01"]').first();
	await link.hover();
	await expect(page.locator('.popover.active-popover')).toBeVisible();
	await page.getByRole('button', { name: 'Toggle dark mode' }).first().click();
	await link.click();
	await page.waitForURL('**/sp26-cs544/lectures/lecture-01');
	await page.waitForTimeout(500);
	expect(errors).toEqual([]);
});

test('Mermaid diagrams retain copy and fullscreen pan/zoom controls', async ({ page }) => {
	await page.goto('/sp26-cs544/lectures/lecture-25');
	const sourceBlocks = page.locator('pre:has(> code.mermaid)');
	const count = await sourceBlocks.count();
	expect(count).toBeGreaterThan(0);

	for (let index = 0; index < count; index++) {
		await sourceBlocks.nth(index).scrollIntoViewIfNeeded();
	}
	// The 200px observer margin can render several adjacent diagrams together.
	await expect(page.locator('.mermaid-inline-content > svg')).toHaveCount(count, {
		timeout: 15_000
	});
	await expect(page.getByRole('button', { name: 'Expand diagram' })).toHaveCount(count);
	await expect(page.getByRole('button', { name: 'Copy diagram source' })).toHaveCount(count);

	await page.getByRole('button', { name: 'Expand diagram' }).first().click();
	const dialog = page.getByRole('dialog', { name: 'Expanded diagram' });
	await expect(dialog).toBeVisible();
	await dialog.getByRole('button', { name: 'Zoom in' }).click();
	await expect(dialog.locator('.mermaid-modal-content')).toHaveAttribute('style', /scale\(1\.1\)/);
	await dialog.getByRole('button', { name: 'Reset zoom' }).click();
	await expect(dialog.locator('.mermaid-modal-content')).toHaveAttribute('style', /scale\(1\)/);
	await page.keyboard.press('Escape');
	await expect(dialog).toBeHidden();
});

test('system theme and heading deep links work', async ({ page }) => {
	await page.goto('/sp26-cs544/lectures/lecture-25');
	await expect(page.locator('html')).not.toHaveClass(/dark/);
	const heading = page.locator('article h2[id]').first();
	const anchor = heading.locator('a.heading-anchor');
	await expect(anchor).toHaveAttribute('href', /^#/);
	await anchor.click();
	await expect(page).toHaveURL(/#.+/);
});

test('Cloudflare asset headers and canonical URLs are configured', async ({ request }) => {
	const pageResponse = await request.get('/sp26-cs544/README');
	expect(pageResponse.headers()['x-content-type-options']).toBe('nosniff');
	expect(pageResponse.headers()['x-frame-options']).toBe('DENY');
	expect(pageResponse.headers()['x-robots-tag']).toContain('noindex');

	const graphResponse = await request.get('/graph.json');
	expect(graphResponse.headers()['cache-control']).toContain('max-age=300');

	const pagefindFilter = readdirSync('.svelte-kit/cloudflare/pagefind/filter')[0];
	const filterResponse = await request.get(`/pagefind/filter/${pagefindFilter}`);
	expect(filterResponse.headers()['cache-control']).toContain('immutable');

	const trailing = await request.get('/sp26-cs544/README/', { maxRedirects: 0 });
	expect(trailing.status()).toBe(307);
	expect(trailing.headers().location).toBe('/sp26-cs544/README');
});
