import { expect, test } from '@playwright/test';
import { readdirSync } from 'node:fs';

test('Pagefind exposes real course and tag filters, including #tag search', async ({ page }) => {
	await page.goto('/sp26-cs544/README');
	const filters = await page.evaluate(async () => {
		// @ts-expect-error generated by Pagefind after the SvelteKit build
		const pagefind = await import('/pagefind/pagefind.js');
		await pagefind.init();
		return pagefind.filters();
	});

	expect(Object.keys(filters.course ?? {})).toContain('sp26-cs544');
	expect(Object.keys(filters.course ?? {})).not.toContainEqual(expect.stringContaining(', tag:'));
	expect(Object.keys(filters.tag ?? {})).toContain('cs544');
	expect(Object.keys(filters.tag ?? {}).length).toBeGreaterThan(150);

	await page.keyboard.press('Control+k');
	await page.getByPlaceholder('Search… or #tag').fill('#cs544');
	await expect(page.getByLabel('Filter by tag')).toContainText('cs544');
	await expect(page.locator('[data-command-group-items]').first()).toBeVisible();
});

test('graph survives the Quartz interaction sequence without browser errors', async ({ page }) => {
	const errors: string[] = [];
	page.on('pageerror', (error) => errors.push(error.stack ?? error.message));

	const prerendered = await page.request.get('/sp26-cs544/README');
	expect(await prerendered.text()).toContain('data-graph-outer');

	await page.goto('/sp26-cs544/README');
	const graph = page.getByRole('region', { name: 'Graph view' });
	const graphOuter = graph.locator('[data-graph-outer]');
	await expect(graphOuter).toBeVisible();
	await expect(graph.getByRole('heading', { name: 'Graph View' })).toBeVisible();
	const graphBox = await graphOuter.boundingBox();
	expect(graphBox?.width ?? 0).toBeGreaterThanOrEqual(315);
	expect(graphBox?.height).toBe(250);

	const toc = page.getByRole('navigation', { name: 'On this page' });
	await expect(toc).toBeVisible();
	const graphPrecedesToc = await graph.evaluate((element) => {
		const tocElement = document.querySelector('nav[aria-label="On this page"]');
		return Boolean(
			tocElement && element.compareDocumentPosition(tocElement) & Node.DOCUMENT_POSITION_FOLLOWING
		);
	});
	expect(graphPrecedesToc).toBe(true);
	const backlinks = page.locator('main [data-island="backlinks"]');
	await expect(backlinks.getByRole('heading', { name: 'Linked to this page' })).toBeVisible();
	await expect(page.locator('.doc-sidebar-right [data-island="backlinks"]')).toHaveCount(0);

	const localCanvas = page.locator('[aria-label="Graph view"] canvas');
	await expect(localCanvas).toBeVisible();
	const graphView = graph.getByRole('img', { name: 'Knowledge graph' });
	await expect(graphView).toHaveAttribute('data-graph-ready', 'true');
	expect(Number(await graphView.getAttribute('data-graph-nodes'))).toBeGreaterThan(1);
	expect(Number(await graphView.getAttribute('data-graph-links'))).toBeGreaterThan(0);
	const box = await localCanvas.boundingBox();
	expect(box?.width ?? 0).toBeGreaterThanOrEqual(313);

	await page.getByRole('button', { name: 'Open global graph' }).click();
	await expect(page.locator('[role="dialog"] canvas')).toBeVisible();
	await page.getByRole('button', { name: 'Close' }).click();

	const link = page.locator('article a.internal[href="/sp26-cs544/lectures/lecture-01"]').first();
	await link.hover();
	await expect(page.locator('.popover.active-popover')).toBeVisible();
	await page.getByRole('button', { name: 'Toggle dark mode' }).first().click();
	await link.click();
	await page.waitForURL('**/sp26-cs544/lectures/lecture-01');
	await page.waitForTimeout(500);
	expect(errors).toEqual([]);
});

test('graph rail follows content at the Quartz tablet breakpoint', async ({ page }) => {
	await page.setViewportSize({ width: 1000, height: 800 });
	await page.goto('/sp26-cs544/README');

	const main = page.locator('main.doc-main');
	const graph = page.getByRole('region', { name: 'Graph view' });
	await expect(graph).toBeVisible();
	await expect(page.getByRole('navigation', { name: 'On this page' })).toBeHidden();

	const mainBox = await main.boundingBox();
	const graphBox = await graph.boundingBox();
	expect(graphBox?.y ?? 0).toBeGreaterThanOrEqual((mainBox?.y ?? 0) + (mainBox?.height ?? 0) - 1);
});

test('Mermaid diagrams retain copy and fullscreen pan/zoom controls', async ({ page }) => {
	await page.goto('/sp26-cs544/lectures/lecture-25');
	const sourceBlocks = page.locator('pre:has(> code.mermaid)');
	const count = await sourceBlocks.count();
	expect(count).toBeGreaterThan(0);

	for (let index = 0; index < count; index++) {
		await sourceBlocks.nth(index).scrollIntoViewIfNeeded();
	}
	// The 200px observer margin can render several adjacent diagrams together.
	await expect(page.locator('.mermaid-inline-content > svg')).toHaveCount(count, {
		timeout: 15_000
	});
	await expect(page.getByRole('button', { name: 'Expand diagram' })).toHaveCount(count);
	await expect(page.getByRole('button', { name: 'Copy diagram source' })).toHaveCount(count);

	await page.getByRole('button', { name: 'Expand diagram' }).first().click();
	const dialog = page.getByRole('dialog', { name: 'Expanded diagram' });
	await expect(dialog).toBeVisible();
	await dialog.getByRole('button', { name: 'Zoom in' }).click();
	await expect(dialog.locator('.mermaid-modal-content')).toHaveAttribute('style', /scale\(1\.1\)/);
	await dialog.getByRole('button', { name: 'Reset zoom' }).click();
	await expect(dialog.locator('.mermaid-modal-content')).toHaveAttribute('style', /scale\(1\)/);
	await page.keyboard.press('Escape');
	await expect(dialog).toBeHidden();
});

test('system theme and heading deep links work', async ({ page }) => {
	await page.goto('/sp26-cs544/lectures/lecture-25');
	await expect(page.locator('html')).not.toHaveClass(/dark/);
	const heading = page.locator('article h2[id]').first();
	const anchor = heading.locator('a.heading-anchor');
	await expect(anchor).toHaveAttribute('href', /^#/);
	await anchor.click();
	await expect(page).toHaveURL(/#.+/);
});

test('Cloudflare asset headers and canonical URLs are configured', async ({ request }) => {
	const pageResponse = await request.get('/sp26-cs544/README');
	expect(pageResponse.headers()['x-content-type-options']).toBe('nosniff');
	expect(pageResponse.headers()['x-frame-options']).toBe('DENY');
	expect(pageResponse.headers()['x-robots-tag']).toContain('noindex');

	const graphResponse = await request.get('/graph.json');
	expect(graphResponse.headers()['cache-control']).toContain('max-age=300');

	const pagefindFilter = readdirSync('.svelte-kit/cloudflare/pagefind/filter')[0];
	const filterResponse = await request.get(`/pagefind/filter/${pagefindFilter}`);
	expect(filterResponse.headers()['cache-control']).toContain('immutable');

	const trailing = await request.get('/sp26-cs544/README/', { maxRedirects: 0 });
	expect(trailing.status()).toBe(307);
	expect(trailing.headers().location).toBe('/sp26-cs544/README');
});
